Test users/people added
CommonGateway/HuwelijksplannerBundle pull request #57
Opened 2023-03-28 12:54 UTC by bbrands02

2023-03-28 14:49 UTC, WilcoLouwerse requested changes

2023-03-28 14:49 UTC, WilcoLouwerse commented on Installation/Schema/hp.taxanomy.schema.json
> +  "$schema": "https://docs.commongateway.nl/schemas/SecurityGroup.schema.json",
Dit lijkt mij niet correct.
https://huwelijksplanner.nl/schemas/hp.taxanomy.schema.json
zou een Entity moeten zijn?

2023-03-28 14:49 UTC, WilcoLouwerse commented on Installation/SecurityGroup/security_groups.json
> +        "anonymous": false,
"anonymous": false
is de default, mag je dus ook niet meegeven

2023-03-28 14:49 UTC, WilcoLouwerse commented on Installation/installation.json
> +        ]
password mag je ook leeg laten, dit toevoegen hier heeft geen invloed namelijk. Default = "!ChangeMe!".

2023-03-30 10:59 UTC, bbrands02 commented on Installation/SecurityGroup/marrying.partner2.securityGroup.json
> +  "title": "Marrying Partner2 SecurityGroup",
Hz partner2 specifiek?

2023-03-30 11:00 UTC, WilcoLouwerse commented on Installation/SecurityGroup/marrying.partner2.securityGroup.json
> +  "title": "Marrying Partner2 SecurityGroup",
Daar vroeg Sarai specifiek om
Blijkbaar mag partner 1 meer dan partner 2

2023-03-30 12:05 UTC, WilcoLouwerse approved these changes
:)

2023-03-30 12:18 UTC, smisidjan approved these changes

2023-03-30 12:18 UTC, merged